version: '3.8'

services:
  app:
    container_name: bot_english
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
        - .:/app
    environment:
      PORT: ${PORT}
    ports:
      - "3002:3002"  # You can adjust the port as needed
    network_mode: "host"
